[package]
name = "rib"
version = "0.1.0"
edition = "2024"

[dependencies]
# Internal representation
chrono = "0.4.42"

# IO
argh = "0.1.13" # Consider trying `clap` as an alternative
cli-table = "0.5.0" # Look more into alternatives
epub = "2.1.5"
sanitize-filename = "0.6.0"
serde = {version = "1.0.228", features = ["derive"]}
serde_json = "1.0.148"
toml = "0.9.10"
url = "2.5.8"
xml = "1.2.0"

# Paths
directories = "6.0.0"
pathdiff = "0.2.3"

# Error handling
anyhow = "1.0.100"

# Convenience
itertools = "0.14.0"
