[package]
name = "rib"
version = "0.1.0"
edition = "2024"

[dependencies]
argh = "0.1.13"
chrono = "0.4.42"
directories = "6.0.0"
epub = "2.1.5"
lazy_static = "1.5.0"
sanitize-filename = "0.6.0"
serde = {version = "1.0.228", features = ["derive"]}
serde_json = "1.0.148"
toml = "0.9.10"
