### Uncomment this to define what program rib defaults to opening your book
### sections in. (If undefined, your system default web browser will be used.)

# default_browser = "firefox"

### The least-recently-opened cached book will be purged when at least one of
### these limits is reached. If the set of books opened in a single program-
### invocation is larger than the maximums set here, the set will remain in the
### library until rib's next run, to avoid making any book or set of books
### impossible to open. Set either of these values to 0 to always clear all
### previously-opened books when opening any new ones.

# max_library_books = 100
max_library_bytes = 1_000_000 # 100 MB

### By default, when a book is opened in rib, it will include an index page
### with links to all the book's sections and table-of-contents-entries. This
### can be disabled by setting include_index to false.

# include_index = false

### By default, when a book is opened in rib, it will include a navigation
### interface around each of its sections, with links to the next section,
### previous section, and (if generated) index. This can be disabled by setting
### inject_navigation to false.

# inject_navigation = false

### List of stylesheets to automatically apply to a book upon opening it. If
### the list is empty, no stylesheet will be applied. If the list contains
### multiple stylesheets, the book will be generated with all of them and will
### be initially opened with the first one specified.

default_stylesheets = ["default_black"]

### Below: definitions for stylesheets which can be applied to books, including
### via the default_stylesheets list above and via command-line flag. Each
### definition is made up of a series of keys whose values map to CSS styles.
### If any key is unset, its associated styles won't be applied, although books'
### own stylesheets and browser default styles will still be present.
###
### Keys which directly specify book styles:
###
### - text_color: CSS color attribute to apply to all book text.
### - link_color: CSS color attribute to apply to book link text, overriding
### text_color as needed.
### - background_color: CSS background-color attribute to apply to book body.
### - margin_size: CSS left and right margin attribute to apply to book body.
### - max_image_width: CSS max-width attribute to apply to images in book.
###
### Override keys: each direct book-style key has a corresponding override key.
### text_color_override, link_color_override, et cetera. If an override key is
### set to true, its associated style will take priority over any stylesheets
### specified in the book. Otherwise, book stylesheets will take precedence.
###
### Each stylesheet is defined by name under the [stylesheets] table:
### [stylesheets.foo] would define a stylesheet named "foo", for instance.

[stylesheets.default_black]
	text_color = "white"
	link_color = "#a8f" # Experiment and see if this should be made lighter
	background_color = "black"
	margin_size = "10%"
	max_image_width = "100%"
	max_image_width_override = true
[stylesheets.default_white]
	text_color = "black"
	link_color = "#51f"
	background_color = "white"
	margin_size = "10%"
	max_image_width = "100%"
	max_image_width_override = true
