### Uncomment this to define what program rib defaults to opening your book
### sections in. (If undefined, your system default web browser will be used.)

# default_browser = "firefox"

### The least-recently-opened cached book will be purged when at least one of
### these limits is reached. If the set of books opened in a single program-
### invocation is larger than the maximums set here, the set will remain in the
### library until rib's next run, to avoid making any book or set of books
### impossible to open. Set either of these values to 0 to always clear all
### previously-opened books when opening any new ones.

# max_library_books = 100
max_library_bytes = 1_000_000 # 100 MB

### By default, when a book is opened in rib, it will include an index page
### with links to all the book's sections and table-of-contents-entries. This
### can be disabled by setting include_index to false.

# include_index = false

### By default, when a book is opened in rib, it will include a navigation
### interface around each of its sections, with links to the next section,
### previous section, and (if generated) index. This can be disabled by setting
### inject_navigation to false.

# inject_navigation = false

### TODO: stylesheets, including index-generation and navigation-injection
